package com.edgedo.bigdata.entity;

import java.util.Date;

public class TeamReceive {
	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 默认主键
	 */
	private String id;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 序列号
	 */
	private Integer orderNumber;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 创建人姓名
	 */
	private String createUserName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 创建人ID
	 */
	private String createUserId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 创建时间
	 */
	private Date createTime;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 操作人
	 */
	private String operator;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 操作时间
	 */
	private Date operateTime;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 版本号
	 */
	private String version;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 复查情况
	 */
	private String reviewCaseQuestion;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 发文编号
	 */
	private String checkCode;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 单位名称
	 */
	private String companyName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 单位地址
	 */
	private String companyAddress;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 检查时间
	 */
	private Date checkTime2;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 检查人员
	 */
	private String checkManName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 检查内容
	 */
	private String checkContent;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 检查情况存在问题
	 */
	private String checkCaseQuestion;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 现场整改
	 */
	private String curChange;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 现场被检查单位责任人
	 */
	private String curChangeChargedManName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 现场整改被检查时间
	 */
	private Date curChangeChargedDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 限期整改
	 */
	private String limitChange;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 限期被检查单位负责人
	 */
	private String limitChangeChargedPerson;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 限期整改时间
	 */
	private Date limitChangeDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 复查人员签字
	 */
	private String reviewCaseManName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 从业人员安全责任
	 */
	private String congyeAnquanZeren;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 安全生产检查制度
	 */
	private String anquanScCheckZd;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 安全生产教育培训制度
	 */
	private String anquanScEduZd;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 安全管理制度
	 */
	private String anquanMngZd;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 应急预案制度
	 */
	private String yingjiYuanZd;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 安全生产作业规程
	 */
	private String anquanScGuicheng;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 安全生产考核制度
	 */
	private String anquanScKhZd;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 安全事故处理制度
	 */
	private String anquanSgclZd;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 灭火器
	 */
	private String fireExtinguisher;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 运管处下发id
	 */
	private String ygcSendId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 备用字段2
	 */
	private String ptDwzState;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 备用字段3
	 */
	private String url;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 备用字段4
	 */
	private String ledgerTypeId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 危险车辆检查
	 */
	private String dangerCarCheckFlag;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 复查时间
	 */
	private Date reviewCaseDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 被检查单位负责人签字
	 */
	private String checkedChargeManName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 被检查单位负责人签字时间
	 */
	private Date checkedChargeDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 检查负责人/人员签字
	 */
	private String checkChargeManName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 检查负责人签字时间
	 */
	private Date checkChargeDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 下发时间
	 */
	private Date sendDate;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 业户ID
	 */
	private String teamId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 业户名
	 */
	private String teamName;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 下发人ID
	 */
	private String sendManId;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 备注
	 */
	private String remark;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 确认状态
	 */
	private String checkState;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 */
	private String checkStateString ;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 确认时间
	 */
	private Date checkTime;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 公章
	 */
	private String officialSeal;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 管理人员安全生产责任制度确认
	 */
	private String mngAnquanZeren;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 灭火器图片
	 */
	private String fireExtinguisherPhoto;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 消防沙
	 */
	private String fireSand;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 消防沙图片
	 */
	private String fireSandPhoto;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 消防锹
	 */
	private String fireSpade;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 消防锹图片
	 */
	private String fireSpadePhoto;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 危险车辆检查
	 */
	private String dangerCarCheck;

	/**
	 * This variable is automatically generated by AutoGenerate for CDP.
	 * @chineseName 新的版本号
	 */
	private String newVersion;
	
	
	//2017.08.17修改
	//管理人员安全图片 MNG_ANQUAN_ZEREN_PHOTO
	private String mngAnquanZerenPhoto;
	//从业人员安全责任图片 CONGYE_ANQUAN_ZEREN_PHOTO
	private String congyeAnquanZerenPhoto;
	//安全生产检查制度图片 ANQUAN_SC_CHECK_ZD_PHOTO
	private String anquanScCheckZdPhoto;
	//安全生产教育培训制度图片 ANQUAN_SC_EDU_ZD_PHOTO
	private String anquanScEduZdPhoto;
	//安全管理制度图片 ANQUAN_MNG_ZD_PHOTO
	private String anquanMngZdPhoto;
	//应急预案制度图片 YINGJI_YUAN_ZD_PHOTO
	private String yingjiYuanZdPhoto;
	//安全生产作业规程图片 ANQUAN_SC_GUICHENG_PHOTO
	private String anquanScGuichengPhoto;
	//安全生产考核制度图片 ANQUAN_SC_KH_ZD_PHOTO
	private String anquanScKhZdPhoto;
	//安全事故处理制度图片 ANQUAN_SGCL_ZD_PHOTO
	private String anquanSgclZdPhoto;
	//is_pass 是否通过
	private  String isPass;
	//县区id
	private String xianQuId;

	//科室id
	private String propId;

	private String cityId;

	public String getCityId() {
		return cityId;
	}

	public void setCityId(String cityId) {
		this.cityId = cityId;
	}

	/**
	 * 各种备注
	 */
	public String getPropId() {
		return propId;
	}

	public void setPropId(String propId) {
		this.propId = propId;
	}

	public String getXianQuId() {
		return xianQuId;
	}

	public void setXianQuId(String xianQuId) {
		this.xianQuId = xianQuId;
	}

	private String  remarkPttz, remarkGlzd,remarkCd,remarkXfqc,remarkCheck;

	public String getIsPass() {
		return isPass;
	}

	public void setIsPass(String isPass) {
		this.isPass = isPass;
	}

	public String getRemarkPttz() {
		return remarkPttz;
	}

	public void setRemarkPttz(String remarkPttz) {
		this.remarkPttz = remarkPttz;
	}

	public String getRemarkGlzd() {
		return remarkGlzd;
	}

	public void setRemarkGlzd(String remarkGlzd) {
		this.remarkGlzd = remarkGlzd;
	}

	public String getRemarkCd() {
		return remarkCd;
	}

	public void setRemarkCd(String remarkCd) {
		this.remarkCd = remarkCd;
	}

	public String getRemarkXfqc() {
		return remarkXfqc;
	}

	public void setRemarkXfqc(String remarkXfqc) {
		this.remarkXfqc = remarkXfqc;
	}

	public String getRemarkCheck() {
		return remarkCheck;
	}

	public void setRemarkCheck(String remarkCheck) {
		this.remarkCheck = remarkCheck;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回默认主键
	 * @return 默认主键
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回序列号
	 * @return 序列号
	 */
	public Integer getOrderNumber() {
		return orderNumber;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回创建人姓名
	 * @return 创建人姓名
	 */
	public String getCreateUserName() {
		return createUserName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回创建人ID
	 * @return 创建人ID
	 */
	public String getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回创建时间
	 * @return 创建时间
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回操作人
	 * @return 操作人
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回操作时间
	 * @return 操作时间
	 */
	public Date getOperateTime() {
		return operateTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回版本号
	 * @return 版本号
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回复查情况
	 * @return 复查情况
	 */
	public String getReviewCaseQuestion() {
		return reviewCaseQuestion;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回发文编号
	 * @return 发文编号
	 */
	public String getCheckCode() {
		return checkCode;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回单位名称
	 * @return 单位名称
	 */
	public String getCompanyName() {
		return companyName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回单位地址
	 * @return 单位地址
	 */
	public String getCompanyAddress() {
		return companyAddress;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回检查时间
	 * @return 检查时间
	 */
	public Date getCheckTime2() {
		return checkTime2;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回检查人员
	 * @return 检查人员
	 */
	public String getCheckManName() {
		return checkManName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回检查内容
	 * @return 检查内容
	 */
	public String getCheckContent() {
		return checkContent;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回检查情况存在问题
	 * @return 检查情况存在问题
	 */
	public String getCheckCaseQuestion() {
		return checkCaseQuestion;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回现场整改
	 * @return 现场整改
	 */
	public String getCurChange() {
		return curChange;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回现场被检查单位责任人
	 * @return 现场被检查单位责任人
	 */
	public String getCurChangeChargedManName() {
		return curChangeChargedManName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回现场整改被检查时间
	 * @return 现场整改被检查时间
	 */
	public Date getCurChangeChargedDate() {
		return curChangeChargedDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回限期整改
	 * @return 限期整改
	 */
	public String getLimitChange() {
		return limitChange;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回限期被检查单位负责人
	 * @return 限期被检查单位负责人
	 */
	public String getLimitChangeChargedPerson() {
		return limitChangeChargedPerson;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回限期整改时间
	 * @return 限期整改时间
	 */
	public Date getLimitChangeDate() {
		return limitChangeDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回复查人员签字
	 * @return 复查人员签字
	 */
	public String getReviewCaseManName() {
		return reviewCaseManName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回从业人员安全责任
	 * @return 从业人员安全责任
	 */
	public String getCongyeAnquanZeren() {
		return congyeAnquanZeren;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回安全生产检查制度
	 * @return 安全生产检查制度
	 */
	public String getAnquanScCheckZd() {
		return anquanScCheckZd;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回安全生产教育培训制度
	 * @return 安全生产教育培训制度
	 */
	public String getAnquanScEduZd() {
		return anquanScEduZd;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回安全管理制度
	 * @return 安全管理制度
	 */
	public String getAnquanMngZd() {
		return anquanMngZd;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回应急预案制度
	 * @return 应急预案制度
	 */
	public String getYingjiYuanZd() {
		return yingjiYuanZd;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回安全生产作业规程
	 * @return 安全生产作业规程
	 */
	public String getAnquanScGuicheng() {
		return anquanScGuicheng;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回安全生产考核制度
	 * @return 安全生产考核制度
	 */
	public String getAnquanScKhZd() {
		return anquanScKhZd;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回安全事故处理制度
	 * @return 安全事故处理制度
	 */
	public String getAnquanSgclZd() {
		return anquanSgclZd;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回灭火器
	 * @return 灭火器
	 */
	public String getFireExtinguisher() {
		return fireExtinguisher;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回备用字段
	 * @return 备用字段
	 */
	public String getYgcSendId() {
		return ygcSendId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回备用字段2
	 * @return 备用字段2
	 */
	public String getPtDwzState() {
		return ptDwzState;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回备用字段3
	 * @return 备用字段3
	 */
	public String getUrl() {
		return url;
	}


	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回复查时间
	 * @return 复查时间
	 */
	public Date getReviewCaseDate() {
		return reviewCaseDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回被检查单位负责人签字
	 * @return 被检查单位负责人签字
	 */
	public String getCheckedChargeManName() {
		return checkedChargeManName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回被检查单位负责人签字时间
	 * @return 被检查单位负责人签字时间
	 */
	public Date getCheckedChargeDate() {
		return checkedChargeDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回检查负责人/人员签字
	 * @return 检查负责人/人员签字
	 */
	public String getCheckChargeManName() {
		return checkChargeManName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回检查负责人签字时间
	 * @return 检查负责人签字时间
	 */
	public Date getCheckChargeDate() {
		return checkChargeDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回下发时间
	 * @return 下发时间
	 */
	public Date getSendDate() {
		return sendDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回业户ID
	 * @return 业户ID
	 */
	public String getTeamId() {
		return teamId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回业户名
	 * @return 业户名
	 */
	public String getTeamName() {
		return teamName;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回下发人ID
	 * @return 下发人ID
	 */
	public String getSendManId() {
		return sendManId;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回备注
	 * @return 备注
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回确认状态
	 * @return 确认状态
	 */
	public String getCheckState() {
		return checkState;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回确认时间
	 * @return 确认时间
	 */
	public Date getCheckTime() {
		return checkTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回公章
	 * @return 公章
	 */
	public String getOfficialSeal() {
		return officialSeal;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回管理人员安全生产责任制度确认
	 * @return 管理人员安全生产责任制度确认
	 */
	public String getMngAnquanZeren() {
		return mngAnquanZeren;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回灭火器图片
	 * @return 灭火器图片
	 */
	public String getFireExtinguisherPhoto() {
		return fireExtinguisherPhoto;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回消防沙
	 * @return 消防沙
	 */
	public String getFireSand() {
		return fireSand;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回消防沙图片
	 * @return 消防沙图片
	 */
	public String getFireSandPhoto() {
		return fireSandPhoto;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回消防锹
	 * @return 消防锹
	 */
	public String getFireSpade() {
		return fireSpade;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回消防锹图片
	 * @return 消防锹图片
	 */
	public String getFireSpadePhoto() {
		return fireSpadePhoto;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回危险车辆检查
	 * @return 危险车辆检查
	 */
	public String getDangerCarCheck() {
		return dangerCarCheck;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>返回新的版本号
	 * @return 新的版本号
	 */
	public String getNewVersion() {
		return newVersion;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置默认主键
	 * @param id 默认主键
	 */
	public void setId(String id) {
		if (id != null) {
			this.id = id.trim();
		} else {
			this.id = id;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置序列号
	 * @param orderNumber 序列号
	 */
	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置创建人姓名
	 * @param createUserName 创建人姓名
	 */
	public void setCreateUserName(String createUserName) {
		if (createUserName != null) {
			this.createUserName = createUserName.trim();
		} else {
			this.createUserName = createUserName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置创建人ID
	 * @param createUserId 创建人ID
	 */
	public void setCreateUserId(String createUserId) {
		if (createUserId != null) {
			this.createUserId = createUserId.trim();
		} else {
			this.createUserId = createUserId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置创建时间
	 * @param createTime 创建时间
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置操作人
	 * @param operator 操作人
	 */
	public void setOperator(String operator) {
		if (operator != null) {
			this.operator = operator.trim();
		} else {
			this.operator = operator;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置操作时间
	 * @param operateTime 操作时间
	 */
	public void setOperateTime(Date operateTime) {
		this.operateTime = operateTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置版本号
	 * @param version 版本号
	 */
	public void setVersion(String version) {
		if (version != null) {
			this.version = version.trim();
		} else {
			this.version = version;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置复查情况
	 * @param reviewCaseQuestion 复查情况
	 */
	public void setReviewCaseQuestion(String reviewCaseQuestion) {
		if (reviewCaseQuestion != null) {
			this.reviewCaseQuestion = reviewCaseQuestion.trim();
		} else {
			this.reviewCaseQuestion = reviewCaseQuestion;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置发文编号
	 * @param checkCode 发文编号
	 */
	public void setCheckCode(String checkCode) {
		if (checkCode != null) {
			this.checkCode = checkCode.trim();
		} else {
			this.checkCode = checkCode;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置单位名称
	 * @param companyName 单位名称
	 */
	public void setCompanyName(String companyName) {
		if (companyName != null) {
			this.companyName = companyName.trim();
		} else {
			this.companyName = companyName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置单位地址
	 * @param companyAddress 单位地址
	 */
	public void setCompanyAddress(String companyAddress) {
		if (companyAddress != null) {
			this.companyAddress = companyAddress.trim();
		} else {
			this.companyAddress = companyAddress;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置检查时间
	 * @param checkTime2 检查时间
	 */
	public void setCheckTime2(Date checkTime2) {
		this.checkTime2 = checkTime2;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置检查人员
	 * @param checkManName 检查人员
	 */
	public void setCheckManName(String checkManName) {
		if (checkManName != null) {
			this.checkManName = checkManName.trim();
		} else {
			this.checkManName = checkManName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置检查内容
	 * @param checkContent 检查内容
	 */
	public void setCheckContent(String checkContent) {
		if (checkContent != null) {
			this.checkContent = checkContent.trim();
		} else {
			this.checkContent = checkContent;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置检查情况存在问题
	 * @param checkCaseQuestion 检查情况存在问题
	 */
	public void setCheckCaseQuestion(String checkCaseQuestion) {
		if (checkCaseQuestion != null) {
			this.checkCaseQuestion = checkCaseQuestion.trim();
		} else {
			this.checkCaseQuestion = checkCaseQuestion;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置现场整改
	 * @param curChange 现场整改
	 */
	public void setCurChange(String curChange) {
		if (curChange != null) {
			this.curChange = curChange.trim();
		} else {
			this.curChange = curChange;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置现场被检查单位责任人
	 * @param curChangeChargedManName 现场被检查单位责任人
	 */
	public void setCurChangeChargedManName(String curChangeChargedManName) {
		if (curChangeChargedManName != null) {
			this.curChangeChargedManName = curChangeChargedManName.trim();
		} else {
			this.curChangeChargedManName = curChangeChargedManName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置现场整改被检查时间
	 * @param curChangeChargedDate 现场整改被检查时间
	 */
	public void setCurChangeChargedDate(Date curChangeChargedDate) {
		this.curChangeChargedDate = curChangeChargedDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置限期整改
	 * @param limitChange 限期整改
	 */
	public void setLimitChange(String limitChange) {
		if (limitChange != null) {
			this.limitChange = limitChange.trim();
		} else {
			this.limitChange = limitChange;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置限期被检查单位负责人
	 * @param limitChangeChargedPerson 限期被检查单位负责人
	 */
	public void setLimitChangeChargedPerson(String limitChangeChargedPerson) {
		if (limitChangeChargedPerson != null) {
			this.limitChangeChargedPerson = limitChangeChargedPerson.trim();
		} else {
			this.limitChangeChargedPerson = limitChangeChargedPerson;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置限期整改时间
	 * @param limitChangeDate 限期整改时间
	 */
	public void setLimitChangeDate(Date limitChangeDate) {
		this.limitChangeDate = limitChangeDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置复查人员签字
	 * @param reviewCaseManName 复查人员签字
	 */
	public void setReviewCaseManName(String reviewCaseManName) {
		if (reviewCaseManName != null) {
			this.reviewCaseManName = reviewCaseManName.trim();
		} else {
			this.reviewCaseManName = reviewCaseManName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置从业人员安全责任
	 * @param congyeAnquanZeren 从业人员安全责任
	 */
	public void setCongyeAnquanZeren(String congyeAnquanZeren) {
		if (congyeAnquanZeren != null) {
			this.congyeAnquanZeren = congyeAnquanZeren.trim();
		} else {
			this.congyeAnquanZeren = congyeAnquanZeren;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置安全生产检查制度
	 * @param anquanScCheckZd 安全生产检查制度
	 */
	public void setAnquanScCheckZd(String anquanScCheckZd) {
		if (anquanScCheckZd != null) {
			this.anquanScCheckZd = anquanScCheckZd.trim();
		} else {
			this.anquanScCheckZd = anquanScCheckZd;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置安全生产教育培训制度
	 * @param anquanScEduZd 安全生产教育培训制度
	 */
	public void setAnquanScEduZd(String anquanScEduZd) {
		if (anquanScEduZd != null) {
			this.anquanScEduZd = anquanScEduZd.trim();
		} else {
			this.anquanScEduZd = anquanScEduZd;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置安全管理制度
	 * @param anquanMngZd 安全管理制度
	 */
	public void setAnquanMngZd(String anquanMngZd) {
		if (anquanMngZd != null) {
			this.anquanMngZd = anquanMngZd.trim();
		} else {
			this.anquanMngZd = anquanMngZd;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置应急预案制度
	 * @param yingjiYuanZd 应急预案制度
	 */
	public void setYingjiYuanZd(String yingjiYuanZd) {
		if (yingjiYuanZd != null) {
			this.yingjiYuanZd = yingjiYuanZd.trim();
		} else {
			this.yingjiYuanZd = yingjiYuanZd;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置安全生产作业规程
	 * @param anquanScGuicheng 安全生产作业规程
	 */
	public void setAnquanScGuicheng(String anquanScGuicheng) {
		if (anquanScGuicheng != null) {
			this.anquanScGuicheng = anquanScGuicheng.trim();
		} else {
			this.anquanScGuicheng = anquanScGuicheng;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置安全生产考核制度
	 * @param anquanScKhZd 安全生产考核制度
	 */
	public void setAnquanScKhZd(String anquanScKhZd) {
		if (anquanScKhZd != null) {
			this.anquanScKhZd = anquanScKhZd.trim();
		} else {
			this.anquanScKhZd = anquanScKhZd;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置安全事故处理制度
	 * @param anquanSgclZd 安全事故处理制度
	 */
	public void setAnquanSgclZd(String anquanSgclZd) {
		if (anquanSgclZd != null) {
			this.anquanSgclZd = anquanSgclZd.trim();
		} else {
			this.anquanSgclZd = anquanSgclZd;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置灭火器
	 * @param fireExtinguisher 灭火器
	 */
	public void setFireExtinguisher(String fireExtinguisher) {
		if (fireExtinguisher != null) {
			this.fireExtinguisher = fireExtinguisher.trim();
		} else {
			this.fireExtinguisher = fireExtinguisher;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置备用字段
	 */
	public void setYgcSendId(String ygcSendId) {
		if (ygcSendId != null) {
			this.ygcSendId = ygcSendId.trim();
		} else {
			this.ygcSendId = ygcSendId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置备用字段2
	 */
	public void setPtDwzState(String ptDwzState) {
		if (ptDwzState != null) {
			this.ptDwzState = ptDwzState.trim();
		} else {
			this.ptDwzState = ptDwzState;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置备用字段3
	 */
	public void setUrl(String url) {
		if (url != null) {
			this.url = url.trim();
		} else {
			this.url = url;
		}
	}


	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置复查时间
	 * @param reviewCaseDate 复查时间
	 */
	public void setReviewCaseDate(Date reviewCaseDate) {
		this.reviewCaseDate = reviewCaseDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置被检查单位负责人签字
	 * @param checkedChargeManName 被检查单位负责人签字
	 */
	public void setCheckedChargeManName(String checkedChargeManName) {
		if (checkedChargeManName != null) {
			this.checkedChargeManName = checkedChargeManName.trim();
		} else {
			this.checkedChargeManName = checkedChargeManName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置被检查单位负责人签字时间
	 * @param checkedChargeDate 被检查单位负责人签字时间
	 */
	public void setCheckedChargeDate(Date checkedChargeDate) {
		this.checkedChargeDate = checkedChargeDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置检查负责人/人员签字
	 * @param checkChargeManName 检查负责人/人员签字
	 */
	public void setCheckChargeManName(String checkChargeManName) {
		if (checkChargeManName != null) {
			this.checkChargeManName = checkChargeManName.trim();
		} else {
			this.checkChargeManName = checkChargeManName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置检查负责人签字时间
	 * @param checkChargeDate 检查负责人签字时间
	 */
	public void setCheckChargeDate(Date checkChargeDate) {
		this.checkChargeDate = checkChargeDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置下发时间
	 * @param sendDate 下发时间
	 */
	public void setSendDate(Date sendDate) {
		this.sendDate = sendDate;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置业户ID
	 * @param teamId 业户ID
	 */
	public void setTeamId(String teamId) {
		if (teamId != null) {
			this.teamId = teamId.trim();
		} else {
			this.teamId = teamId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置业户名
	 * @param teamName 业户名
	 */
	public void setTeamName(String teamName) {
		if (teamName != null) {
			this.teamName = teamName.trim();
		} else {
			this.teamName = teamName;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置下发人ID
	 * @param sendManId 下发人ID
	 */
	public void setSendManId(String sendManId) {
		if (sendManId != null) {
			this.sendManId = sendManId.trim();
		} else {
			this.sendManId = sendManId;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置备注
	 * @param remark 备注
	 */
	public void setRemark(String remark) {
		if (remark != null) {
			this.remark = remark.trim();
		} else {
			this.remark = remark;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置确认状态
	 * @param checkState 确认状态
	 */
	public void setCheckState(String checkState) {
		if (checkState != null) {
			this.checkState = checkState.trim();
		} else {
			this.checkState = checkState;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置确认时间
	 * @param checkTime 确认时间
	 */
	public void setCheckTime(Date checkTime) {
		this.checkTime = checkTime;
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置公章
	 * @param officialSeal 公章
	 */
	public void setOfficialSeal(String officialSeal) {
		if (officialSeal != null) {
			this.officialSeal = officialSeal.trim();
		} else {
			this.officialSeal = officialSeal;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置管理人员安全生产责任制度确认
	 * @param mngAnquanZeren 管理人员安全生产责任制度确认
	 */
	public void setMngAnquanZeren(String mngAnquanZeren) {
		if (mngAnquanZeren != null) {
			this.mngAnquanZeren = mngAnquanZeren.trim();
		} else {
			this.mngAnquanZeren = mngAnquanZeren;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置灭火器图片
	 * @param fireExtinguisherPhoto 灭火器图片
	 */
	public void setFireExtinguisherPhoto(String fireExtinguisherPhoto) {
		if (fireExtinguisherPhoto != null) {
			this.fireExtinguisherPhoto = fireExtinguisherPhoto.trim();
		} else {
			this.fireExtinguisherPhoto = fireExtinguisherPhoto;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置消防沙
	 * @param fireSand 消防沙
	 */
	public void setFireSand(String fireSand) {
		if (fireSand != null) {
			this.fireSand = fireSand.trim();
		} else {
			this.fireSand = fireSand;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置消防沙图片
	 * @param fireSandPhoto 消防沙图片
	 */
	public void setFireSandPhoto(String fireSandPhoto) {
		if (fireSandPhoto != null) {
			this.fireSandPhoto = fireSandPhoto.trim();
		} else {
			this.fireSandPhoto = fireSandPhoto;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置消防锹
	 * @param fireSpade 消防锹
	 */
	public void setFireSpade(String fireSpade) {
		if (fireSpade != null) {
			this.fireSpade = fireSpade.trim();
		} else {
			this.fireSpade = fireSpade;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置消防锹图片
	 * @param fireSpadePhoto 消防锹图片
	 */
	public void setFireSpadePhoto(String fireSpadePhoto) {
		if (fireSpadePhoto != null) {
			this.fireSpadePhoto = fireSpadePhoto.trim();
		} else {
			this.fireSpadePhoto = fireSpadePhoto;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置危险车辆检查
	 * @param dangerCarCheck 危险车辆检查
	 */
	public void setDangerCarCheck(String dangerCarCheck) {
		if (dangerCarCheck != null) {
			this.dangerCarCheck = dangerCarCheck.trim();
		} else {
			this.dangerCarCheck = dangerCarCheck;
		}
	}

	/**
	 * This method is automatically generated by AutoGenerate for CDP.
	 * <p>设置新的版本号
	 * @param newVersion 新的版本号
	 */
	public void setNewVersion(String newVersion) {
		if (newVersion != null) {
			this.newVersion = newVersion.trim();
		} else {
			this.newVersion = newVersion;
		}
	}

	//2017.08.17修改
	public String getMngAnquanZerenPhoto() {
		return mngAnquanZerenPhoto;
	}

	public void setMngAnquanZerenPhoto(String mngAnquanZerenPhoto) {
		this.mngAnquanZerenPhoto = mngAnquanZerenPhoto;
	}

	public String getCongyeAnquanZerenPhoto() {
		return congyeAnquanZerenPhoto;
	}

	public void setCongyeAnquanZerenPhoto(String congyeAnquanZerenPhoto) {
		this.congyeAnquanZerenPhoto = congyeAnquanZerenPhoto;
	}

	public String getAnquanScCheckZdPhoto() {
		return anquanScCheckZdPhoto;
	}

	public void setAnquanScCheckZdPhoto(String anquanScCheckZdPhoto) {
		this.anquanScCheckZdPhoto = anquanScCheckZdPhoto;
	}

	public String getAnquanScEduZdPhoto() {
		return anquanScEduZdPhoto;
	}

	public void setAnquanScEduZdPhoto(String anquanScEduZdPhoto) {
		this.anquanScEduZdPhoto = anquanScEduZdPhoto;
	}

	public String getAnquanMngZdPhoto() {
		return anquanMngZdPhoto;
	}

	public void setAnquanMngZdPhoto(String anquanMngZdPhoto) {
		this.anquanMngZdPhoto = anquanMngZdPhoto;
	}

	public String getYingjiYuanZdPhoto() {
		return yingjiYuanZdPhoto;
	}

	public void setYingjiYuanZdPhoto(String yingjiYuanZdPhoto) {
		this.yingjiYuanZdPhoto = yingjiYuanZdPhoto;
	}

	public String getAnquanScGuichengPhoto() {
		return anquanScGuichengPhoto;
	}

	public void setAnquanScGuichengPhoto(String anquanScGuichengPhoto) {
		this.anquanScGuichengPhoto = anquanScGuichengPhoto;
	}

	public String getAnquanScKhZdPhoto() {
		return anquanScKhZdPhoto;
	}

	public void setAnquanScKhZdPhoto(String anquanScKhZdPhoto) {
		this.anquanScKhZdPhoto = anquanScKhZdPhoto;
	}

	public String getAnquanSgclZdPhoto() {
		return anquanSgclZdPhoto;
	}

	public void setAnquanSgclZdPhoto(String anquanSgclZdPhoto) {
		this.anquanSgclZdPhoto = anquanSgclZdPhoto;
	}

	public void setCheckStateString(String checkStateString) {
		this.checkStateString = checkStateString;
	}

	public String getLedgerTypeId() {
		return ledgerTypeId;
	}

	public void setLedgerTypeId(String ledgerTypeId) {
		this.ledgerTypeId = ledgerTypeId;
	}

	public String getDangerCarCheckFlag() {
		return dangerCarCheckFlag;
	}

	public void setDangerCarCheckFlag(String dangerCarCheckFlag) {
		this.dangerCarCheckFlag = dangerCarCheckFlag;
	}
}