CREATE TABLE `bigdata_alarm_record20191` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_alarm_record20192` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_alarm_record20193` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_alarm_record20194` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_alarm_record20195` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_alarm_record20196` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );



CREATE TABLE `bigdata_alarm_record20197` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_alarm_record20198` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_alarm_record20199` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_alarm_record201910` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_alarm_record201911` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );



CREATE TABLE `bigdata_alarm_record201912` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_alarm_record20201` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_alarm_record20202` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record20203` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record20204` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record20205` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record20206` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record20207` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record20208` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record20209` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record202010` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record202011` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
`IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


   CREATE TABLE `bigdata_alarm_record202012` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `B_ID` varchar(50) DEFAULT NULL COMMENT '业务主键',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '运营商id',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名称',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号码',
  `CAR_PLATE_COLOR` varchar(20) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_TYPE` varchar(20) DEFAULT NULL COMMENT '车辆类型',
  `SIM_CODE` varchar(20) DEFAULT NULL COMMENT 'SIM卡号',
  `ALARM_TYPE` varchar(50) DEFAULT NULL COMMENT '报警类型（报警类型 1线路报警2超速报警3紧急报警4疲劳驾驶）',
  `ALARM_TIME` datetime DEFAULT NULL COMMENT '报警时间',
  `DRIVER` varchar(50) DEFAULT NULL COMMENT '司机',
  `LONGITUDE` decimal(16,7) DEFAULT NULL COMMENT '经度',
  `LATITUDE` decimal(16,7) DEFAULT NULL COMMENT '纬度',
  `ALARM_CLS` varchar(10) DEFAULT NULL COMMENT '报警种类(1平台 2终端)',
  `ALARM_SPEED` decimal(16,2) DEFAULT NULL COMMENT '报警速度',
  `ROAD_LEVEL` varchar(50) DEFAULT NULL COMMENT '道路等级',
  `ROAD_SPEED_LIMIT` decimal(16,2) DEFAULT NULL COMMENT '道路限速值',
  `ALARM_TIME_INFO` varchar(100) DEFAULT NULL COMMENT '时长',
  `ALARM_TIME_SECOND` decimal(16,2) DEFAULT NULL COMMENT '时长秒',
  `SERIOUS_FLAG` varchar(10) DEFAULT NULL COMMENT '是否严重',
  `DANGER_TIME_FLAG` varchar(10) DEFAULT NULL COMMENT '是否是危险时段',
  `ALARM_STATE` varchar(20) DEFAULT NULL COMMENT '报警状态(报警状态 0未处理1系统处理2人工处理)',
  `DEAL_TYPE` varchar(50) DEFAULT NULL COMMENT '处理类型',
  `DEAL_REMARK` varchar(300) DEFAULT NULL COMMENT '处理备注',
  `DEAL_TIME` datetime DEFAULT NULL COMMENT '处理时间',
  `DATA_QUALIFIED` varchar(20) DEFAULT NULL COMMENT '数据是否合格',
  `FAIL_REASON` varchar(300) DEFAULT NULL COMMENT '不合格原因',
  `LOCATION_INFO_DESC` varchar(300) DEFAULT NULL,
  `LOCATION_INFO_SIMPLE` varchar(300) DEFAULT NULL,
  `COUNT_DATE` int(11) NOT NULL ,
  `COUNT_MONTH` int(10) NOT NULL ,
 `IS_READ_LOCATION` varchar(20) DEFAULT NULL,
  `IS_LOCALPLACE` varchar(10) DEFAULT NULL,
`IS_HIGH_WAY` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

