
CREATE TABLE `bigdata_driver_count_month_and_year2019` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '所属运营商',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名',
  `TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业',
  `TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '企业名',
  `PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '省ID',
  `PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '省名',
  `CITY_ID` varchar(50) DEFAULT NULL COMMENT '城市ID',
  `CITY_NAME` varchar(20) DEFAULT NULL COMMENT '城市名',
  `XIANQU_ID` varchar(50) DEFAULT NULL COMMENT '县区ID',
  `XIANQU_NAME` varchar(20) DEFAULT NULL COMMENT '县区名',
  `DRIVER_ID` varchar(50) DEFAULT NULL COMMENT '驾驶员ID',
  `DRIVER_NAME` varchar(20) DEFAULT NULL COMMENT '驾驶员姓名',
  `DRIVER_SEX` varchar(10) DEFAULT NULL COMMENT '驾驶员性别',
  `DRIVER_AGE` int(11) DEFAULT NULL COMMENT '驾驶员年龄',
  `DRIVER_PHONE` varchar(20) DEFAULT NULL COMMENT '驾驶员电话',
  `DRIVER_ID_CARD` varchar(50) DEFAULT NULL COMMENT '驾驶员身份证号',
  `DRIVER_CODE` varchar(50) DEFAULT NULL COMMENT '驾驶员资格证号',
  `NATIONAL_ROAD_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '国道里程',
  `HIGH_SPEED_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '高速里程',
  `OTHER_ROAD_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '其他道路里程',
  `DAY_RUN_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '白天行驶里程',
  `NIGHT_RUN_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '夜晚行驶里程',
  `DANGER_RUN_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '危险时段行驶里程',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `DAY_RUN_TIME_LENGTH` decimal(16,2) DEFAULT NULL COMMENT '白天行驶时长(分钟)',
  `NIGHT_RUN_TIME_LENGTH` decimal(16,2) DEFAULT NULL COMMENT '夜晚行驶时长(分钟)',
  `DANGER_RUN_TIME_LENGTH` decimal(16,2) DEFAULT NULL COMMENT '危险时段行驶时长',
  `SUM_RUN_TIME_LENGTH` decimal(16,2) DEFAULT NULL COMMENT '总时长',
  `DAY_RUN_AVERAGE_SPEED` decimal(16,2) DEFAULT NULL COMMENT '白天行驶平均速度',
  `NIGHT_RUN_AVERAGE_SPEED` decimal(16,2) DEFAULT NULL COMMENT '夜晚行驶平均速度',
  `DANGER_RUN_AVERAGE_SPEED` decimal(16,2) DEFAULT NULL COMMENT '危险时段行驶平均速度',
  `AVERAGE_SPEED` decimal(16,2) DEFAULT NULL COMMENT '平均速度',
  `HIGHEST_SPEED` decimal(16,2) DEFAULT NULL COMMENT '最高速度',
  `OVERSPEED_NUM` int(11) DEFAULT NULL COMMENT '超速次数',
  `SERIOUS_OVERSPEED_NUM` int(11) DEFAULT NULL COMMENT '严重超速次数',
  `TIRED_NUM` int(11) DEFAULT NULL COMMENT '疲劳次数',
  `SERIOUS_TIRED_NUM` int(11) DEFAULT NULL COMMENT '严重疲劳次数',
  `SAFETY_WARNING_NUM` int(11) DEFAULT NULL COMMENT '主动安全报警次数',
  `SAFETRAIN_NUM` int(11) DEFAULT NULL COMMENT '安全培训次数',
  `WARNING_RATE` decimal(16,2) DEFAULT NULL COMMENT '百公里报警系数',
  `COUNT_TYPE` varchar(10) DEFAULT NULL COMMENT '统计类型',
  `COUNT_DATE` int(11) DEFAULT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) NOT NULL COMMENT '统计月份',
  `YEAR_NUM` int(11) DEFAULT NULL COMMENT '统计年份',
    PRIMARY KEY (`ID`,`COUNT_MONTH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_MONTH%100)(
      partition p1 values less than (2),
      partition p2 values less than (3),
      partition p3 values less than (4),
      partition p4 values less than (5),
      partition p5 values less than (6),
      partition p6 values less than (7),
      partition p7 values less than (8),
      partition p8 values less than (9),
      partition p9 values less than (10),
      partition p10 values less than (11),
      partition p11 values less than (12),
      partition p12 values less than MAXVALUE
   );



CREATE TABLE `bigdata_driver_count_month_and_year2020` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `COMP_ID` varchar(50) DEFAULT NULL COMMENT '所属运营商',
  `COMP_NAME` varchar(50) DEFAULT NULL COMMENT '运营商名',
  `TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业',
  `TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '企业名',
  `PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '省ID',
  `PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '省名',
  `CITY_ID` varchar(50) DEFAULT NULL COMMENT '城市ID',
  `CITY_NAME` varchar(20) DEFAULT NULL COMMENT '城市名',
  `XIANQU_ID` varchar(50) DEFAULT NULL COMMENT '县区ID',
  `XIANQU_NAME` varchar(20) DEFAULT NULL COMMENT '县区名',
  `DRIVER_ID` varchar(50) DEFAULT NULL COMMENT '驾驶员ID',
  `DRIVER_NAME` varchar(20) DEFAULT NULL COMMENT '驾驶员姓名',
  `DRIVER_SEX` varchar(10) DEFAULT NULL COMMENT '驾驶员性别',
  `DRIVER_AGE` int(11) DEFAULT NULL COMMENT '驾驶员年龄',
  `DRIVER_PHONE` varchar(20) DEFAULT NULL COMMENT '驾驶员电话',
  `DRIVER_ID_CARD` varchar(50) DEFAULT NULL COMMENT '驾驶员身份证号',
  `DRIVER_CODE` varchar(50) DEFAULT NULL COMMENT '驾驶员资格证号',
  `NATIONAL_ROAD_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '国道里程',
  `HIGH_SPEED_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '高速里程',
  `OTHER_ROAD_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '其他道路里程',
  `DAY_RUN_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '白天行驶里程',
  `NIGHT_RUN_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '夜晚行驶里程',
  `DANGER_RUN_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '危险时段行驶里程',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `DAY_RUN_TIME_LENGTH` decimal(16,2) DEFAULT NULL COMMENT '白天行驶时长(分钟)',
  `NIGHT_RUN_TIME_LENGTH` decimal(16,2) DEFAULT NULL COMMENT '夜晚行驶时长(分钟)',
  `DANGER_RUN_TIME_LENGTH` decimal(16,2) DEFAULT NULL COMMENT '危险时段行驶时长',
  `SUM_RUN_TIME_LENGTH` decimal(16,2) DEFAULT NULL COMMENT '总时长',
  `DAY_RUN_AVERAGE_SPEED` decimal(16,2) DEFAULT NULL COMMENT '白天行驶平均速度',
  `NIGHT_RUN_AVERAGE_SPEED` decimal(16,2) DEFAULT NULL COMMENT '夜晚行驶平均速度',
  `DANGER_RUN_AVERAGE_SPEED` decimal(16,2) DEFAULT NULL COMMENT '危险时段行驶平均速度',
  `AVERAGE_SPEED` decimal(16,2) DEFAULT NULL COMMENT '平均速度',
  `HIGHEST_SPEED` decimal(16,2) DEFAULT NULL COMMENT '最高速度',
  `OVERSPEED_NUM` int(11) DEFAULT NULL COMMENT '超速次数',
  `SERIOUS_OVERSPEED_NUM` int(11) DEFAULT NULL COMMENT '严重超速次数',
  `TIRED_NUM` int(11) DEFAULT NULL COMMENT '疲劳次数',
  `SERIOUS_TIRED_NUM` int(11) DEFAULT NULL COMMENT '严重疲劳次数',
  `SAFETY_WARNING_NUM` int(11) DEFAULT NULL COMMENT '主动安全报警次数',
  `SAFETRAIN_NUM` int(11) DEFAULT NULL COMMENT '安全培训次数',
  `WARNING_RATE` decimal(16,2) DEFAULT NULL COMMENT '百公里报警系数',
  `COUNT_TYPE` varchar(10) DEFAULT NULL COMMENT '统计类型',
  `COUNT_DATE` int(11) DEFAULT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) NOT NULL COMMENT '统计月份',
  `YEAR_NUM` int(11) DEFAULT NULL COMMENT '统计年份',
    PRIMARY KEY (`ID`,`COUNT_MONTH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_MONTH%100)(
      partition p1 values less than (2),
      partition p2 values less than (3),
      partition p3 values less than (4),
      partition p4 values less than (5),
      partition p5 values less than (6),
      partition p6 values less than (7),
      partition p7 values less than (8),
      partition p8 values less than (9),
      partition p9 values less than (10),
      partition p10 values less than (11),
      partition p11 values less than (12),
      partition p12 values less than MAXVALUE
   );