CREATE TABLE `bigdata_safety_warning_file20198` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20199` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file201910` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file201911` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file201912` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20201` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20202` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20203` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20204` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20205` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20206` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20207` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20208` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_safety_warning_file20209` (
  `Id` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `OWNER_SAFETY_WARNING_ID` varchar(50) DEFAULT NULL COMMENT '所属安全预警Id',
  `CAR_PLATE_NUM` varchar(16) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(32) DEFAULT NULL COMMENT '车架号',
  `FILE_NAME` varchar(100) DEFAULT NULL COMMENT '文件名',
  `FILE_TYPE` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `FILE_URL` varchar(200) DEFAULT NULL COMMENT '路径',
  `REMARK` varchar(100) DEFAULT NULL COMMENT '备注',
  `IS_DOWNLOAD` varchar(10) DEFAULT NULL COMMENT '是否下载',
  `COUNT_DATE` int(11) NOT NULL COMMENT '统计日期',
  `COUNT_MONTH` int(11) DEFAULT NULL COMMENT '统计月份',
   PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


