CREATE TABLE `bigdata_car_day_oftenrun_route20191` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20192` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20193` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20194` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20195` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20196` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route20197` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route20198` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route20199` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route201910` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route201911` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route201912` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20201` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20202` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20203` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20204` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20205` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

CREATE TABLE `bigdata_car_day_oftenrun_route20206` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route20207` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route20208` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route20209` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route202010` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route202011` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );


CREATE TABLE `bigdata_car_day_oftenrun_route202012` (
  `ID` varchar(50) NOT NULL COMMENT '主键',
  `CREATE_TIME` datetime DEFAULT NULL COMMENT '创建时间',
  `CAR_PLATE_NUM` varchar(20) DEFAULT NULL COMMENT '车牌号',
  `CAR_FRAME_NUM` varchar(50) DEFAULT NULL COMMENT '车架号',
  `CAR_PLATE_COLOR` varchar(10) DEFAULT NULL COMMENT '车牌颜色',
  `CAR_REAL_ID` varchar(50) DEFAULT NULL COMMENT '关联车辆id',
  `OWNER_TEAM_ID` varchar(50) DEFAULT NULL COMMENT '所属企业ID',
  `OWNER_TEAM_NAME` varchar(50) DEFAULT NULL COMMENT '所属企业名',
  `START_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '出发省ID',
  `START_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '出发省名',
  `END_PROVINCE_ID` varchar(50) DEFAULT NULL COMMENT '目的省ID',
  `END_PROVINCE_NAME` varchar(20) DEFAULT NULL COMMENT '目的省名',
  `START_CITY_ID` varchar(50) DEFAULT NULL COMMENT '出发城市ID',
  `START_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '出发城市名',
  `END_CITY_ID` varchar(50) DEFAULT NULL COMMENT '目的城市ID',
  `END_CITY_NAME` varchar(20) DEFAULT NULL COMMENT '目的城市名',
  `START_TIME` datetime DEFAULT NULL COMMENT '开始时间',
  `END_TIME` datetime DEFAULT NULL COMMENT '结束时间',
  `RUN_ROUTE` varchar(100) DEFAULT NULL COMMENT '路线',
  `SUM_MILEAGE` decimal(16,2) DEFAULT NULL COMMENT '总里程',
  `CAR_TYPE` varchar(10) DEFAULT NULL COMMENT '车辆类型',
  `COUNT_TIME` datetime DEFAULT NULL COMMENT '统计时间',
  `COUNT_DATE` int(11) NOT NULL,
  `COUNT_MONTH` int(11) DEFAULT NULL,
  `IS_TRANS_PROVINCIAL` varchar(10) DEFAULT NULL COMMENT '是否跨省',
  `RUN_LINE_NUM` int(11) DEFAULT NULL COMMENT '当日线路次数',
  PRIMARY KEY (`ID`,`COUNT_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
   partition by range(COUNT_DATE%100)(
     partition p1 values less than (2),
     partition p2 values less than (3),
     partition p3 values less than (4),
     partition p4 values less than (5),
     partition p5 values less than (6),
     partition p6 values less than (7),
     partition p7 values less than (8),
     partition p8 values less than (9),
     partition p9 values less than (10),
     partition p10 values less than (11),
     partition p11 values less than (12),
     partition p12 values less than (13),
     partition p13 values less than (14),
     partition p14 values less than (15),
     partition p15 values less than (16),
     partition p16 values less than (17),
     partition p17 values less than (18),
     partition p18 values less than (19),
     partition p19 values less than (20),
     partition p20 values less than (21),
     partition p21 values less than (22),
     partition p22 values less than (23),
     partition p23 values less than (24),
     partition p24 values less than (25),
     partition p25 values less than (26),
     partition p26 values less than (27),
     partition p27 values less than (28),
     partition p28 values less than (29),
     partition p29 values less than (30),
     partition p30 values less than (31),
     partition p31 values less than MAXVALUE
   );

